# Generated by Django 4.2 on 2023-05-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='occupation',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Business', 'Business'), ('farmer', 'farmer'), ('Doctor', 'Doctor'), ('others', 'others')], max_length=25, null=True),
        ),
    ]
